# include theme
include ./poimandres.conf

# Font
font_family FiraCode Nerd Font
bold_font auto
italic_font auto
bold_italic_font auto

# Hide title bar
# hide_window_decorations True
allow_remote_control yes

background_opacity 0.85
